<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="TermsOfUse.aspx.cs" Inherits="BarteRoom.TermsOfUse" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="termsPage">
        <h1>Terms Of Use</h1>
              
     These Terms of Use constitute an agreement (the “Agreement”) between you (“You”) and eBay Inc., a Delaware corporation (“eBay” or “we”), relating to Your use of this Application (as defined below), which may allow You to facilitate certain social interactions in connection with Your online shopping or other internet-enabled activities (“Help Me Shop”). Please read this Agreement carefully. By using Help Me Shop, You agree to be bound by terms and conditions set forth in this Agreement, and Your use of this Application is also subject to the www.ebay.com Privacy Policy and User Agreement (collectively, the “Terms”). Certain features of this Application may require You to be a member of eBay’s or third-parties’ websites, or provide personal information as part of a registration process, and such membership, registration and/or information disclosure may be governed by additional terms and conditions set forth on such websites. Third parties that own or operate any such websites are not responsible for this Application or the content thereof.
1.	DEFINITIONS.
“Application” means a desktop application, browser plug-in or so-called “bookmarklet” made available to You for installation, download or use in connection with Help Me Shop, and any updates or revised or upgraded versions of any such application, plug-in or bookmarklet.
“Content” means all content residing in the Application, excluding the Data.
“Data” means all data, information, functionality and content that You upload to or post on the Application, or is uploaded and posted on Your behalf, including, but not limited to, poll questions, product specifications, product descriptions, reviews, photographs, images, Marks and other user-generated content. “Data” includes, without limitation, Data that You have uploaded from your device(s) and Data that You elect to post from third party websites.
“eBay Sites” means www.ebay.com and any other url(s) maintained by or on behalf of eBay or its affiliates.
“Intellectual Property” means, with respect to any software, code, data or other asset of any kind, all copyright, patent, trademark, trade secret, moral rights, termination, authorship and other proprietary rights now known or hereafter developed, or applications for any of the foregoing rights, relating to any such software, code, data or other asset, including, without limitation, all rights necessary for the worldwide development, manufacture, modification, enhancement, sale, licensing, use, reproduction, publishing and display of such software, code, data or other asset.
“Marks” means any trademarks, service marks, names, logos, or other graphics or branding elements.
2. IMPLEMENTATION. eBay may make available to You an Application in connection with Help Me Shop. If You elect to install, download or use the Application, You agree that this Agreement does not grant You any Intellectual Property in or to the Application, and any copies You might make of the Application, other than a limited, personal right to use the Application in connection with Your Help Me Shop activities that will terminate upon the termination of this Agreement. You acknowledge that Your use of the Application is voluntary and at Your own risk. You may not: (a) modify, copy, publish, license, sell or otherwise commercialize this Application or any Content or software associated with this Application; (b) rent, lease or otherwise transfer rights to this Application; or (c) use this Application in any manner that could impair any eBay Site in any way or interfere with any third party’s use or enjoyment of any eBay Site. eBay makes no guarantees with respect to the availability or uptime of the Application. eBay may conduct maintenance on or change the method of access to the Application, at any time with or without notice to You.
3.	DATA RIGHTS & OBLIGATIONS.
You represent that any Data that You upload to or post on the Application shall be free from any spyware, malware, virus, worm, Trojan horse, or other malicious or harmful code, and that You own or otherwise have the unconditional right to upload or post such Data. You hereby grant to eBay and its affiliates a non-exclusive, worldwide, perpetual, irrevocable, limited, royalty-free, sub-licensable (through multiple tiers) and transferable right and license to exercise the copyright, trademark, patent, publicity, database, and all other Intellectual Property rights in the Data, as well as the right to host, cache, route, transmit, store, copy, modify, reproduce, distribute, publish, translate, use, publicly perform, publicly display, reformat, excerpt, analyze, and create derivative works of the Data, in any media known now or in the future, including any eBay Site, or application or other property owned, operated or provided by eBay or its affiliates. 

eBay may elect to not display Data (or any portion thereof), in its sole discretion. Additionally, eBay reserves the right to remove any Data from any media on which it is displayed at any time, with or without notice to You, if, in its sole opinion, such Data conflicts with or is in breach of this Agreement or the nature or quality of the Data is inconsistent with eBay’s mission or standards. There are no implied licenses from eBay under this Agreement.
4.	APPLICATION USE.
While using the Application, You will not:
violate any laws, third party rights or eBay’s policies, such as these Prohibited and Restricted Items policies;
use our sites, services or tools if You are not able to form legally binding contracts, are under the age of 18, or are temporarily or indefinitely suspended from using any of our sites, services or tools;
post false, inaccurate, misleading, defamatory, or libelous content (including personal information);
distribute or post spam, unsolicited, or bulk electronic communications, chain letters, or pyramid schemes;
distribute viruses or any other technologies that may harm eBay, or the interests or property of eBay users;
copy, modify or distribute Content or eBay’s Marks; or
harvest or otherwise collect information about individuals, including email addresses, without their consent.
Please report problems, offensive content, and policy violations to eBay using the feedback feature in the Application. Without limiting other remedies, eBay may limit, suspend or terminate Application access, service and/or user accounts, prohibit access to our sites and their content (including the Application and the Content), services and tools, delay or remove hosted content, and take technical and legal steps to keep users off the Application if eBay suspects that they are creating problems or possible legal liabilities, infringing the intellectual property rights of third parties, or acting inconsistently with the letter or spirit of our policies. eBay also reserves the right to modify or discontinue the Application and any other websites, services or tools associated with Help Me Shop.
eBay’s Verified Rights Owner (VeRO) program works to ensure that items displayed on eBay Sites do not infringe upon the copyright, trademark or other intellectual property rights of third parties. If You believe that Your Intellectual Property rights have been violated in connection with the Application or Help Me Shop, please notify our VeRO team through our Verified Rights Owner (VeRO) Program and we will investigate. Additionally, eBay may, in appropriate circumstances and at our discretion, suspend or terminate accounts of users who may be repeat infringers of intellectual property rights of third parties.
This Application may utilize social networking or “share functionality” or may contain links to third party sites that are not owned or controlled by eBay. eBay has no control over, and assumes no responsibility for, any share or other social media functionality provided by third parties, or the content, privacy policies, or practices of any third party website. You are subject to the policies of those third parties when and where applicable. By using this Application, You expressly relieve eBay from any and all liability arising from Your use of any share or other social media functionality or third party website accessed from this Application. Upon receipt of notice addressed to eBay as directed below, we will delete any data about You, if any, that we receive from certain third parties’ websites that provide such social media functionality and, in the event that we receive such notice from You, this Agreement will terminate automatically without further notice to You.
5.	INDEMNIFICATION. You will indemnify and hold eBay (and our affiliates and our and their officers, directors, agents, subsidiaries, joint ventures and employees) harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of Your breach of this Agreement, or Your violation of any law or the rights of a third party in connection with the Data, Application or Help Me Shop.
6.	DISCLAIMER OF WARRANTIES. EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW, (I) EBAY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING, WITHOUT LIMITATION, ANY AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, ACCURACY, RESULTS OF USE, RELIABILITY, TITLE, INTERFERENCE WITH QUIET ENJOYMENT, NON-INFRINGEMENT OF THIRD-PARTY RIGHTS, FITNESS FOR A PARTICULAR PURPOSE OR OTHER BENEFIT THAT YOU MIGHT OBTAIN THROUGH YOUR PARTICIPATION IN THIS AGREEMENT AND (II) THE APPLICATION IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGES TO YOUR HARDWARE DEVICE(S) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF THIS APPLICATION. FURTHER, EBAY DISCLAIMS ANY WARRANTY THAT USE OF THE APPLICATION WILL BE UNINTERRUPTED OR ERROR FREE. YOU ACKNOWLEDGE THAT PRODUCTS THAT MAY BE DISPLAYED IN THE CONTENT ARE SOLD BY THIRD PARTY MERCHANTS, NOT BY EBAY. THE CONTENT MAY CONTAIN LINKS TO THIRD PARTY WEBSITES THAT ARE SELLING DISPLAYED PRODUCTS, AND THOSE THIRD PARTY WEBSITES MAY BE SUBJECT TO ADDITIONAL TERMS OF USE. YOU ACKNOWLEDGE AND AGREE THAT EBAY IS NOT RESPONSIBLE OR LIABLE FOR THE AVAILABILITY OR ACCURACY OF SUCH THIRD PARTY WEBSITES, OR FOR THE CONTENT, PRODUCTS OR SERVICES ON OR AVAILABLE FROM SUCH WEBSITES. EBAY DOES NOT GUARANTEE THE ACCURACY OF CONTENT, AND WILL NOT ASSUME ANY LIABILITY FOR APPLICATION USERS’ (1) PURCHASE DECISIONS (AND THE SUBSEQUENT USE OF PURCHASED PRODUCTS AND SERVICES) THAT MAY BE INFORMED BY, THE INFORMATION PROVIDED IN THE APPLICATION OR ITS CONTENT OR (2) THIRD PARTIES’ CONTENT, ACTIONS OR INACTIONS, OR YOUR INTERACTIONS WITH ANY THIRD PARTIES IN CONNECTION WITH THE APPLICATION OR HELP ME SHOP. IF YOU HAVE A DISPUTE WITH ONE OR MORE THIRD PARTIES IN CONNECTION WITH YOUR USE OF THE APPLICATION OR HELP ME SHOP, YOU RELEASE US (AND OUR OFFICERS, DIRECTORS, AGENTS, SUBSIDIARIES, JOINT VENTURES AND EMPLOYEES) FROM CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES. IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE §1542, WHICH SAYS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”
7.	LIMITATION OF LIABILITY. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON LIABILITY. ONLY LIMITATIONS THAT ARE LAWFUL IN THE APPLICABLE JURISDICTION WILL APPLY TO YOU AND EBAY'S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. EBAY WILL HAVE NO DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, EXEMPLARY, STATUTORY, PUNITIVE, OR OTHER LIABILITY WHETHER IN CONTRACT, TORT OR ANY OTHER LEGAL THEORY, UNDER THIS AGREEMENT OR OTHERWISE IN CONNECTION WITH THE APPLICATION OR HELP ME SHOP, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH LIABILITY AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. IN THE EVENT THAT THE ABOVE IS NOT ENFORCEABLE, EBAY’S AGGREGATE LIABILITY UNDER THIS AGREEMENT OR OTHERWISE IN CONNECTION WITH THE APPLICATION OR HELP ME SHOP IS LIMITED TO $100. THE FOREGOING LIMITATIONS SHALL APPLY TO ALL CLAIMS ARISING FROM THIS AGREEMENT, THE APPLICATION AND/OR HELP ME SHOP.
8.	TERM, SUSPENSION, TERMINATION, SURVIVAL. The term of this Agreement will begin on the date on which You accept this Agreement online. It will continue until terminated in accordance with this Agreement. If You wish to terminate this Agreement, You must uninstall and delete the Application, and any copy thereof, and cease all use of the Application and Help Me Shop; any other methods used by You to terminate the Agreement will be void and will not result in a termination. In addition, this Agreement will terminate automatically without notice if You fail to comply with any of its terms. The right to use the Application that is granted hereunder is dependent on Your compliance with this Agreement and terminates automatically if You fail to comply with the terms. eBay reserves the right to terminate or suspend this Agreement for any or no reason at any time upon notice to You and without liability to You. Notwithstanding the expiration or termination of this Agreement, the following Sections shall survive termination of this Agreement: 5, 6, 7, 10, 11 and any other sections that expressly indicate they are to survive, such as this paragraph.
9.	TERMS CHANGE. eBay reserves the right to make changes to this Application or Terms from time to time. Any material changes will take effect immediately for new users and upon the expiration of thirty (30) days after posting within the Application for current users. If You do not agree to any change, please uninstall and discontinue using this Application. Any use of this Application after the thirty (30) day notice period constitutes Your acceptance of any change.
10.	CHOICE OF LAW. The Agreement shall be deemed to have been made in and shall be construed pursuant to the laws of the State of California without regard to conflicts of laws provisions thereof and without regard to the U.N. Convention on the International Sale of Goods. Any disputes related to this Agreement shall be resolved in the state or federal courts located in Santa Clara County, California, to whose sole and exclusive jurisdiction and venue the parties hereto irrevocably submit.
11.	MISCELLANEOUS
eBay does not sell or rent Your personal information to third parties for their marketing purposes without Your explicit consent. eBay uses Your information only as described in the eBay Privacy Policy. eBay stores and processes Your information on computers located in the United States that are protected by physical as well as technological security devices. You can access and modify certain information You provide eBay, as enabled by the Application’s functionalities. eBay uses third parties to verify and certify our privacy principles. For a complete description of how eBay uses and protects Your personal information, see the eBay Privacy Policy. If You object to Your information being transferred or used in this way please do not use the Application.
Any notice to eBay must be sent to 2145 Hamilton Avenue, San Jose, CA 95125, Attention: General Counsel, via first class or air mail or overnight courier, and is deemed given upon receipt.
No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by this Agreement. There are no third-party beneficiaries hereunder.
If any provision of the Agreement shall be adjudged by any court of competent jurisdiction to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that the Agreement shall otherwise remain in full force and effect and enforceable.
You are responsible for complying with trade regulations and both foreign and domestic laws. You represent and warrant that You are not located in a country that is subject to a US Government embargo, or that has been designated by the US Government as a “terrorist supporting” country and You are not listed on any US Government list of prohibited or restricted parties. This Application or its underlying technology may not be downloaded to or exported or re-exported: (a) into (or to a resident or national of) Cuba, Iraq, Iran, Libya, North Korea, Syria or any other country subject to United States embargo; (b) to anyone on the US Treasury Department’s list of Specially Designated Nationals or on the US Commerce Department’s Denied Party or Entity List; and (c) You will not export or re-export this Application to any prohibited country, person, end-user or entity specified by US Export Laws.
Date of last revision: june 28, 2015.
    </div>
</asp:Content>

